//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 11/03/2016 14:13:02
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace BikeSharing.Client.Kiosk.UWP.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Kiosk
    {
        
        private static ResourceLoader resourceLoader;
        
        static Kiosk()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Kiosk).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Kiosk");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Kiosk");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "OK, {0}. I've unlocked a bike for you from the rack and debited your account."
        /// </summary>
        public static string bike_unlocked
        {
            get
            {
                return resourceLoader.GetString("bike_unlocked");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sorry {0}, there's some issue in the transaction.  I could not unlock a bike for you."
        /// </summary>
        public static string checkout_failed
        {
            get
            {
                return resourceLoader.GetString("checkout_failed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Hey you! Come over here!"
        /// </summary>
        public static string come_over
        {
            get
            {
                return resourceLoader.GetString("come_over");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "By the way, it's beautiful out today, why aren't you smiling?"
        /// </summary>
        public static string emotion_prompt
        {
            get
            {
                return resourceLoader.GetString("emotion_prompt");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "That's much better, enjoy your ride!"
        /// </summary>
        public static string enjoy_ride
        {
            get
            {
                return resourceLoader.GetString("enjoy_ride");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sorry I could not retrieve your profile at this time."
        /// </summary>
        public static string fail_to_retrieve_profile
        {
            get
            {
                return resourceLoader.GetString("fail_to_retrieve_profile");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "{0}, welcome back!"
        /// </summary>
        public static string greeting
        {
            get
            {
                return resourceLoader.GetString("greeting");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Hi there, unfortunately I don't know you. Please register using our mobile app first to be able to rent a bike."
        /// </summary>
        public static string new_customer
        {
            get
            {
                return resourceLoader.GetString("new_customer");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "This session will be reset."
        /// </summary>
        public static string reset
        {
            get
            {
                return resourceLoader.GetString("reset");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sorry, I didn't understand you. What can I do for you?"
        /// </summary>
        public static string unrecognized_intent
        {
            get
            {
                return resourceLoader.GetString("unrecognized_intent");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Voice verification failed."
        /// </summary>
        public static string voice_verification_attempt_failed
        {
            get
            {
                return resourceLoader.GetString("voice_verification_attempt_failed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Thank you, your voice verification was successful!"
        /// </summary>
        public static string voice_verification_attempt_passed
        {
            get
            {
                return resourceLoader.GetString("voice_verification_attempt_passed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sorry, I couldn't verify you."
        /// </summary>
        public static string voice_verification_failed
        {
            get
            {
                return resourceLoader.GetString("voice_verification_failed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Could you speak your verification phrase?"
        /// </summary>
        public static string voice_verification_prompt
        {
            get
            {
                return resourceLoader.GetString("voice_verification_prompt");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Please speak your secret phrase within the next {0} seconds."
        /// </summary>
        public static string voice_verification_prompt_2
        {
            get
            {
                return resourceLoader.GetString("voice_verification_prompt_2");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "So {0}, what would you like to do?"
        /// </summary>
        public static string what_to_do
        {
            get
            {
                return resourceLoader.GetString("what_to_do");
            }
        }
    }
}
